### ISSUE TITLE
Google is shutting down Inbox 😢

### ISSUE THREAD

**Issue by squidfunk** [fgnass/inbox-app#15]
Yesterday [Google announced](https://www.theverge.com/2018/9/12/17848500/google-inbox-shut-down-sunset-snooze-email-march-2019) it will be shutting down Inbox at the end of March 2019. That is in fact very sad news, as I really enjoyed using it, especially in form of this awesome Electron app.

Where shall we go now? Gmail clearly sucks.

**Comment by fgnass** [comment]
I made another electron app to make Gmail suck a little less: https://github.com/fgnass/gmail-app
