### ISSUE TITLE
Why you only create app for OS X not for windows or linux?

### ISSUE THREAD

**Issue by Birju** [fgnass/inbox-app#5]
Are you facing any challenge to make same application for windows and linux?

**Comment by ildella** [comment]
this works on linux. I just cloned, run "npm install" then "npm start". Is even easier then on OSX ;)

**Comment by redoxeon** [comment]
any chance it'll work on windows soon?

**Comment by fgnass** [comment]
It already does, sorry for not closing this issue earlier!
